### PR TITLE
add maps by widardd

### PR DESCRIPTION
**Pull request by widardd**
Requires at least Fortune Avenue v9 beta 5 for the Event Square on some maps.

### CODE REVIEW

**Review by Deflaktor — CHANGES_REQUESTED** [review]
Review: 
The map pusteblume crashes with an error messsage: 
grafik

The autopilot got stuck at this place in the map spin:
grafik
And crash too at the map spin: 
grafik

Crash at : 
grafik


Some of the maps minimaps go out of bounds:
grafik
grafik
grafik
grafik

**Comment by Hubcapp** [comment]
I personally don't really consider it a problem if the board selection preview goes out of bounds as long as the map is playable.

**Comment by widardd** [comment]
Pusteblume aswell as Spin work fine here on Dolphin, finished each, but immediately freeze original hardware. Will try to investigating what's going on. The remaining crashes are probably pathing mistakes and loops I seem to tend to create, thanks! ;)

**Comment by Deflaktor** [comment]
HI widardd, I added Metamorphosis to the new repository and converted it to the new .yaml format. The other maps still crashed for me. If you want to upload more maps again, please use the new repository. The maps are now located here: https://fortunestreetmodding.github.io/maps

**Pull request closed without merging**
